---
# tasks file for ansible_haproxy
- name: Get service facts.
  ansible.builtin.service_facts:

- name: Ensure HAProxy and other required packages are installed.
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - haproxy
    - socat

- name: Ensure the HAProxy service is enabled and started.
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: "SELinux - Ensure haproxy can connect to all TCP ports."
  ansible.builtin.seboolean:
    name: haproxy_connect_any
    persistent: yes
    state: "{{ haproxy_connect_all_ports }}"
  notify: restart haproxy
    
- name: Ensure HAProxy is configured correctly.
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart haproxy

- name: Make sure required firewalld rules are in place
  ansible.builtin.firewalld:
    port: "{{ haproxy_frontend_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true
  when: ansible_facts.services["firewalld.service"] is defined