---
# tasks file for ansible_haproxy
- name: Get service facts.
  ansible.builtin.service_facts:

- name: Ensure HAProxy and other required packages are installed.
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - haproxy
    - socat

- name: Ensure the HAProxy service is enabled and started.
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: "SELinux - Ensure haproxy can connect to all TCP ports."
  ansible.builtin.seboolean:
    name: haproxy_connect_any
    persistent: yes
    state: "{{ haproxy_connect_all_ports }}"
    
#- name: Ensure HAProxy is configured correctly.
#  ansible.builtin.template:
#    src: haproxy.cfg.j2
#    dest: /etc/haproxy/haproxy.cfg
#  notify: restart haproxy

#- name: Enable port {{ rh_demo_web_app_listen_port }} in firewalld
#  ansible.builtin.firewalld:
#    port: "{{ haproxy_frontend_port }}/tcp"
#    permanent: yes
#    immediate: true
#    state: enabled
#  when: "'firewalld.service' in services"